
Memory Configuration

Name             Origin             Length             Attributes
FLASH            0x08000000         0x00020000         xr
SRAM             0x20000000         0x00005000         xrw
*default*        0x00000000         0xffffffff

Linker script and memory map

LOAD ./Output/EXTI.o
LOAD ./Output/GPIO.o
LOAD ./Output/RCC.o
LOAD ./Output/TIM.o
LOAD ./Output/main.o
LOAD ./Output/stm32_startup.o

.text           0x08000000      0x958
 *(.isr_vector)
 .isr_vector    0x08000000      0x188 ./Output/stm32_startup.o
                0x08000000                vectors
 *(.text*)
 .text          0x08000188      0x2bc ./Output/EXTI.o
                0x08000188                EXTI0_IRQHandler
                0x080001b4                get_Pin_Number
                0x080001f0                EXTI_Init
                0x0800040c                NVIC_UART_En
                0x08000428                NVIC_USB_En
 .text          0x08000444      0x198 ./Output/GPIO.o
                0x08000444                GPIO_Config
                0x08000586                GPIO_Write_Pin
                0x080005b4                GPIO_Read_Pin
 .text          0x080005dc      0x1cc ./Output/RCC.o
                0x080005dc                RCC_Config_72Mhz
                0x08000690                RCC_Enable_PortA
                0x080006ac                RCC_Enable_PortB
                0x080006c8                RCC_Enable_PortC
                0x080006e4                RCC_Enable_AFIO
                0x08000700                RCC_Enable_TIM2
                0x0800071c                RCC_Enable_ADC01
                0x08000738                RCC_Enable_UART1
                0x08000754                RCC_Enable_SPI1
                0x08000770                RCC_Enable_I2C1
                0x0800078c                RCC_Enable_USB
 .text          0x080007a8       0xe0 ./Output/TIM.o
                0x080007a8                TIM2_init_IT
                0x080007fc                TIM2_IRQHandler
                0x08000824                delay_ms
 .text          0x08000888       0x40 ./Output/main.o
                0x08000888                main
 .text          0x080008c8       0x90 ./Output/stm32_startup.o
                0x080008c8                Reset_Handler
                0x08000950                HASH_RNG_IRQHandler
                0x08000950                EXTI2_IRQHandler
                0x08000950                TIM8_CC_IRQHandler
                0x08000950                DebugMon_Handler
                0x08000950                TIM1_CC_IRQHandler
                0x08000950                DMA2_Stream5_IRQHandler
                0x08000950                HardFault_Handler
                0x08000950                DMA1_Stream5_IRQHandler
                0x08000950                SysTick_Handler
                0x08000950                PVD_IRQHandler
                0x08000950                SDIO_IRQHandler
                0x08000950                TAMP_STAMP_IRQHandler
                0x08000950                PendSV_Handler
                0x08000950                NMI_Handler
                0x08000950                CAN2_RX1_IRQHandler
                0x08000950                EXTI3_IRQHandler
                0x08000950                TIM8_TRG_COM_TIM14_IRQHandler
                0x08000950                TIM1_UP_TIM10_IRQHandler
                0x08000950                TIM8_UP_TIM13_IRQHandler
                0x08000950                I2C3_ER_IRQHandler
                0x08000950                I2C2_EV_IRQHandler
                0x08000950                DMA1_Stream2_IRQHandler
                0x08000950                CAN1_RX0_IRQHandler
                0x08000950                FPU_IRQHandler
                0x08000950                OTG_HS_WKUP_IRQHandler
                0x08000950                UsageFault_Handler
                0x08000950                CAN2_SCE_IRQHandler
                0x08000950                DMA2_Stream2_IRQHandler
                0x08000950                SPI1_IRQHandler
                0x08000950                TIM6_DAC_IRQHandler
                0x08000950                TIM1_BRK_TIM9_IRQHandler
                0x08000950                DCMI_IRQHandler
                0x08000950                CAN2_RX0_IRQHandler
                0x08000950                DMA2_Stream3_IRQHandler
                0x08000950                USART6_IRQHandler
                0x08000950                USART3_IRQHandler
                0x08000950                CRYP_IRQHandler
                0x08000950                RTC_Alarm_IRQHandler
                0x08000950                CAN1_RX1_IRQHandler
                0x08000950                UART5_IRQHandler
                0x08000950                DMA2_Stream0_IRQHandler
                0x08000950                TIM4_IRQHandler
                0x08000950                I2C1_EV_IRQHandler
                0x08000950                DMA1_Stream6_IRQHandler
                0x08000950                DMA1_Stream1_IRQHandler
                0x08000950                UART4_IRQHandler
                0x08000950                TIM3_IRQHandler
                0x08000950                RCC_IRQHandler
                0x08000950                TIM8_BRK_TIM12_IRQHandler
                0x08000950                Default_Handler
                0x08000950                EXTI15_10_IRQHandler
                0x08000950                ADC_IRQHandler
                0x08000950                DMA1_Stream7_IRQHandler
                0x08000950                TIM7_IRQHandler
                0x08000950                CAN2_TX_IRQHandler
                0x08000950                TIM5_IRQHandler
                0x08000950                DMA2_Stream7_IRQHandler
                0x08000950                I2C3_EV_IRQHandler
                0x08000950                EXTI9_5_IRQHandler
                0x08000950                RTC_WKUP_IRQHandler
                0x08000950                ETH_WKUP_IRQHandler
                0x08000950                SPI2_IRQHandler
                0x08000950                OTG_HS_EP1_IN_IRQHandler
                0x08000950                MemManage_Handler
                0x08000950                DMA1_Stream0_IRQHandler
                0x08000950                CAN1_TX_IRQHandler
                0x08000950                SVC_Handler
                0x08000950                EXTI4_IRQHandler
                0x08000950                FSMC_IRQHandler
                0x08000950                ETH_IRQHandler
                0x08000950                OTG_HS_EP1_OUT_IRQHandler
                0x08000950                WWDG_IRQHandler
                0x08000950                OTG_FS_WKUP_IRQHandler
                0x08000950                TIM1_TRG_COM_TIM11_IRQHandler
                0x08000950                OTG_HS_IRQHandler
                0x08000950                EXTI1_IRQHandler
                0x08000950                USART2_IRQHandler
                0x08000950                I2C2_ER_IRQHandler
                0x08000950                DMA2_Stream1_IRQHandler
                0x08000950                CAN1_SCE_IRQHandler
                0x08000950                DMA2_Stream4_IRQHandler
                0x08000950                BusFault_Handler
                0x08000950                USART1_IRQHandler
                0x08000950                OTG_FS_IRQHandler
                0x08000950                SPI3_IRQHandler
                0x08000950                DMA1_Stream4_IRQHandler
                0x08000950                I2C1_ER_IRQHandler
                0x08000950                DMA2_Stream6_IRQHandler
                0x08000950                DMA1_Stream3_IRQHandler
 *(.rodata*)
                0x08000958                . = ALIGN (0x4)
                0x08000958                _etext = .

.glue_7         0x08000958        0x0
 .glue_7        0x08000958        0x0 linker stubs

.glue_7t        0x08000958        0x0
 .glue_7t       0x08000958        0x0 linker stubs

.vfp11_veneer   0x08000958        0x0
 .vfp11_veneer  0x08000958        0x0 linker stubs

.v4_bx          0x08000958        0x0
 .v4_bx         0x08000958        0x0 linker stubs

.iplt           0x08000958        0x0
 .iplt          0x08000958        0x0 ./Output/EXTI.o

.rel.dyn        0x08000958        0x0
 .rel.iplt      0x08000958        0x0 ./Output/EXTI.o

.data           0x20000000        0x0 load address 0x08000958
                0x20000000                _sdata = .
 *(.data*)
 .data          0x20000000        0x0 ./Output/EXTI.o
 .data          0x20000000        0x0 ./Output/GPIO.o
 .data          0x20000000        0x0 ./Output/RCC.o
 .data          0x20000000        0x0 ./Output/TIM.o
 .data          0x20000000        0x0 ./Output/main.o
 .data          0x20000000        0x0 ./Output/stm32_startup.o
                0x20000000                . = ALIGN (0x4)
                0x20000000                _edata = .

.igot.plt       0x20000000        0x0 load address 0x08000958
 .igot.plt      0x20000000        0x0 ./Output/EXTI.o

.bss            0x20000000        0x0 load address 0x08000958
                0x20000000                _sbss = .
 *(.bss*)
 .bss           0x20000000        0x0 ./Output/EXTI.o
 .bss           0x20000000        0x0 ./Output/GPIO.o
 .bss           0x20000000        0x0 ./Output/RCC.o
 .bss           0x20000000        0x0 ./Output/TIM.o
 .bss           0x20000000        0x0 ./Output/main.o
 .bss           0x20000000        0x0 ./Output/stm32_startup.o
                0x20000000                . = ALIGN (0x4)
                0x20000000                _ebss = .
OUTPUT(./Output/makefile.elf elf32-littlearm)
LOAD linker stubs

.comment        0x00000000       0x49
 .comment       0x00000000       0x49 ./Output/EXTI.o
                                 0x4a (size before relaxing)
 .comment       0x00000049       0x4a ./Output/GPIO.o
 .comment       0x00000049       0x4a ./Output/RCC.o
 .comment       0x00000049       0x4a ./Output/TIM.o
 .comment       0x00000049       0x4a ./Output/main.o
 .comment       0x00000049       0x4a ./Output/stm32_startup.o

.ARM.attributes
                0x00000000       0x2d
 .ARM.attributes
                0x00000000       0x2d ./Output/EXTI.o
 .ARM.attributes
                0x0000002d       0x2d ./Output/GPIO.o
 .ARM.attributes
                0x0000005a       0x2d ./Output/RCC.o
 .ARM.attributes
                0x00000087       0x2d ./Output/TIM.o
 .ARM.attributes
                0x000000b4       0x2d ./Output/main.o
 .ARM.attributes
                0x000000e1       0x2d ./Output/stm32_startup.o
